### ISSUE TITLE
Input data from `incidence2`

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/datadelay#39]
`datadelay`'s functions to estimate CFR require a specific df format of date-onset-death columns. When using `incidence2` to go from a linelist to the daily cases/death counts, these counts can be obtained in one step, but this results in a df with a long format (i.e. the variables "onset_date" and "death" appear as rows rather than columns), and it is then necessary to pivot the table so that this could be used as input for `datadelay`. 
Alternatively, users could extract the case/death counts separately using `incidence2` and then merge them into a new dataset, or attempt to do this manually without using this package.
In any of these cases, I think that it will be quite tedious for users to have to add these many lines of code to their scripts, for such a predictable task.
I believe it would be very useful to add a function to provide a df with the right format in one step, I'm unsure of which package this would belong to, whether `incidence2` or `datadelay`, but after a conversation with @Bisaloo I'm raising it here for wider discussion.

**Comment by Bisaloo** [comment]
To add to Carmen's point from a different point of view:

incidence2 is designed to provide a standard data structure for count data. If we want to encourage and spread its usage in the wider ecosystem, we should lead the way in our own packages by providing a custom S3 method for incidence objects.

**Comment by pratikunterwegs** [comment]
Thanks all for the discussion and Carmen for raising this.

I like Tim's suggestion of a `prepare_data()` generic with a method for `<incidence2>` objects.

Could I get some ideas on other methods, e.g. for `<linelist>`s (assuming they do not use {incidence2} for some reason - or would we prefer to force such usage?).

**Comment by pratikunterwegs** [comment]
Could I get some feedback as to how the `prepare_data()` method should handle grouping in `<incidence2>` objects?

Currently, I am ignoring grouping and summing cases and deaths by date for different groups with a message if groups are detected.

Users might expect us to respect grouping structure, but I think that {datadelay} (and most of our packages) should stay away from data science-y capabilities. Users could implement the glue between data with many groups and {datadelay} in their own workflows, or we could do it in an {episoap} workflow.

If we do decide to respect grouping structure, it would be worth pulling in data wranging dependencies, and since the candidate data input formats are Tidyverse-based (e.g. `<incidence2>`, `<linelist>`), it might be worth pulling in {dplyr} and {tidyr}.

Pinging @TimTaylor and @CarmenTamayo and @Bisaloo for (eventual) input.

**Comment by Bisaloo** [comment]
Can we open another issue for the incidence2 grouping discussion please to make sure this stays on our radar? I think it's an important point.
